export default {
  GET_PRESS_LIST_REQUEST: "GET_PRESS_LIST_REQUEST",
  SET_PRESS_LIST: "SET_PRESS_LIST",
  TOOGLE_PRESS_LIST_LOADER: "TOOGLE_PRESS_LIST_LOADER",
  UPDATE_PRESS_PAGE_NUMBER: "UPDATE_PRESS_PAGE_NUMBER",
  HANDLE_DELETE_PRESS_REQUEST: "HANDLE_DELETE_PRESS_REQUEST",
  HANDLE_PRESS_DELETE_LOADING: "HANDLE_PRESS_DELETE_LOADING",
  HANDLE_PRESS_EDIT: "HANDLE_PRESS_EDIT",
};
