export default {
  GET_STORES_OF_USER_REQUEST: "GET_STORES_OF_USER_REQUEST",
  SET_STORES: "SET_STORES",
  SET_STORES_UNCLAIMED: "SET_STORES_UNCLAIMED",
  ADD_NEW_STORE_REQUEST: "ADD_NEW_STORE_REQUEST",
  TOOGLE_STORE_CREATE_LOADER: "TOOGLE_STORE_CREATE_LOADER",
  TOOGLE_STORE_LIST_LOADER: "TOOGLE_STORE_LIST_LOADER",
  TOOGLE_STORES_LIST_LOADER: "TOOGLE_STORES_LIST_LOADER",
  HANDLE_STORE_EDIT_LOAD_REQUEST: "HANDLE_STORE_EDIT_LOAD_REQUEST",
  HANDLE_EDIT_LOADING: "HANDLE_EDIT_LOADING",
  HANDLE_STORE_EDIT: "HANDLE_STORE_EDIT",
  HANDLE_STORE_DELETE: "HANDLE_STORE_DELETE",
  HANDLE_DELETE_STORE_IMAGE_REQUEST: "HANDLE_DELETE_STORE_IMAGE_REQUEST",
  HANDLE_STORE_DELETE_LOADING: "HANDLE_STORE_DELETE_LOADING"
};
