export default {
  GET_BLOG_LIST_REQUEST: "GET_BLOG_LIST_REQUEST",
  SET_BLOG_LIST: "SET_BLOG_LIST",
  TOOGLE_BLOG_LIST_LOADER: "TOOGLE_BLOG_LIST_LOADER",
  UPDATE_BLOG_PAGE_NUMBER: "UPDATE_BLOG_PAGE_NUMBER",
  HANDLE_DELETE_BLOG_REQUEST: "HANDLE_DELETE_BLOG_REQUEST",
  HANDLE_BLOG_DELETE_LOADING: "HANDLE_BLOG_DELETE_LOADING",
  HANDLE_BLOG_EDIT: "HANDLE_BLOG_EDIT",
};
