export default {
	GET_PRODUCT_LISTINGS_REQUEST: "GET_PRODUCT_LISTINGS_REQUEST",
	SET_PRODUCTS_LISTS: "SET_PRODUCTS_LISTS",
	ADD_NEW_PRODUCT_REQUEST: "ADD_NEW_PRODUCT_REQUEST",
	TOOGLE_PRODUCT_CREATE_LOADER: "TOOGLE_PRODUCT_CREATE_LOADER",
	TOOGLE_PRODUCT_LIST_LOADER: "TOOGLE_PRODUCT_LIST_LOADER",
	HANDLE_DELETE_PRODUCT_REQUEST: "HANDLE_DELETE_PRODUCT_REQUEST",
	HANDLE_PRODUCT_DELETE_LOADING: "HANDLE_PRODUCT_DELETE_LOADING",

	HANDLE_PRODUCT_EDIT: "HANDLE_PRODUCT_EDIT",
	HANDLE_PRODUCT_EDIT_REQUEST: "HANDLE_PRODUCT_EDIT_REQUEST",
	HANDLE_EDIT_LOADING: "HANDLE_EDIT_LOADING",
	HANDLE_DELETE_PRODUCT_IMAGE_REQUEST: "HANDLE_DELETE_PRODUCT_IMAGE_REQUEST",

	HANDLE_CARD_DATA_REQUEST: "HANDLE_CARD_DATA_REQUEST",
};
