export default {
  GET_STORE_PRODUCTS_OF_USER_REQUEST: "GET_STORE_PRODUCTS_OF_USER_REQUEST",
  SET_STORES_PRODUCTS: "SET_STORES_PRODUCTS",
  ADD_NEW_STORE_PRODUCT_REQUEST: "ADD_NEW_STORE_PRODUCT_REQUEST",
  TOOGLE_PRODUCT_CREATE_LOADER: "TOOGLE_PRODUCT_CREATE_LOADER",
  TOOGLE_PRODUCT_LIST_LOADER: "TOOGLE_PRODUCT_LIST_LOADER",
  HANDLE_DELETE_STORE_PRODUCT_REQUEST: "HANDLE_DELETE_STORE_PRODUCT_REQUEST",
  HANDLE_PRODUCT_DELETE_LOADING: "HANDLE_PRODUCT_DELETE_LOADING",
  HANDLE_STORE_PRODUCT_EDIT: "HANDLE_STORE_PRODUCT_EDIT",
  HANDLE_STORE_PRODUCT_EDIT_REQUEST: "HANDLE_STORE_PRODUCT_EDIT_REQUEST",
  HANDLE_STORE_PRODUCT_EDIT_LOADING: "HANDLE_STORE_PRODUCT_EDIT_LOADING",
  HANDLE_DELETE_PRODUCT_IMAGE_REQUEST: "HANDLE_DELETE_PRODUCT_IMAGE_REQUEST",
};
