export default {
  GET_BLOG_PRESS_LIST_REQUEST: "GET_BLOG_PRESS_LIST_REQUEST",
  SET_BLOG_PRESS_LIST: "SET_BLOG_PRESS_LIST",
  TOOGLE_BLOG_PRESS_LIST_LOADER: "TOOGLE_BLOG_PRESS_LIST_LOADER",
  UPDATE_PAGE_NUMBER: "UPDATE_PAGE_NUMBER",
  HANDLE_DELETE_BLOG_PRESS_REQUEST: "HANDLE_DELETE_BLOG_PRESS_REQUEST",
  HANDLE_BLOG_PRESS_DELETE_LOADING: "HANDLE_BLOG_PRESS_DELETE_LOADING",
  HANDLE_BLOG_EDIT: "HANDLE_BLOG_EDIT",
};
