export default {
  GET_COUPON_LIST_REQUEST: "GET_COUPON_LIST_REQUEST",
  SET_COUPON_LIST: "SET_COUPON_LIST",
  TOOGLE_COUPON_LIST_LOADER: "TOOGLE_COUPON_LIST_LOADER",
  UPDATE_COUPON_PAGE_NUMBER: "UPDATE_COUPON_PAGE_NUMBER",
  HANDLE_DELETE_COUPON_REQUEST: "HANDLE_DELETE_COUPON_REQUEST",
  HANDLE_COUPON_DELETE_LOADING: "HANDLE_COUPON_DELETE_LOADING",
  HANDLE_COUPON_EDIT: "HANDLE_COUPON_EDIT",
};
